export const GET_ALL_GAMES = "GET_ALL_GAMES";
export const GET_GAMES_BY_NAME = "GET_GAMES_BY_NAME";

export const SET_NAV_FATHER = "SET_NAV_FATHER";
export const SET_ALL_GENRES = "SET_ALL_GENRES";
export const SET_GAME_DETAIL = "SET_GAME_DETAIL";
export const SET_ALL_PLATFORMS = "SET_ALL_PLATFORMS";

export const CLEAN_STATE = "CLEAN_STATE";
export const CLEAN_DETAIL = "CLEAN_DETAIL";